package by.htp.jwd.command;

public enum CommandName {
	LOGINATION, INDEXVIEW, REGISTRATION, SAVEUSER, ADDNEWCARVIEW, ADDNEWCAR, ALLCARSVIEW, CHOOSECARVIEW,
	TOLOGINATIONPAGE, LOOKINGCAR, LOCALIZATION, INFOCAR, TOPAYPAGE, LOGOUT, PAYFORCAR, TOFORGOTPASSWORDPAGE,
	FORGOTPASSWORD, TOFINDPAGE, TOCABINETPAGE, ADDODER, ADDREPAIRBILLVIEW, TOREPAIRBILLPAGE, ADDREPAIRBILL,
	REPORTREPAIRBILL, TOUPDATEUSERPAGE, UPDATEUSER, REPORTODERBYUSER, CANCELODERBYUSER, REPORTREPAIRBYUSER,
	REPORTALLCAR, TOUPDATECARPAGE, UPDATECAR, TOINFOPAGE, TOPAYREPAIRBILLPAGE, PAYFORREPAIRBILL, DELETECAR,
	TOCANCELODERPAGE, CANCELODER, COMPLETEDORDER, TOPAYMAENTCONTACTPAGE, UPDATEINFOPAGE, ADDADRESS, TOADDADRESSPAGE
}
